## Q. 1. Create a null vector of size 10 but the fifth value which is 1.

In [29]:
import numpy as np
a = np.zeros(10)
print(f"All values of a: {a}")
a[5] = 1
print(f"Updated values of a: {a}")

All values of a: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated values of a: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## Q. 2. Create a vector with values ranging from 10 to 49.

In [8]:
arr = np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

## Q.3.Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr1 = np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Q.4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
num = [1,2,0,0,4,0]
non_zeros = np.nonzero(num)
print(non_zeros)

(array([0, 1, 4], dtype=int64),)


## Q.5.Create a 10x10 array with random values and find the minimum and maximum values.

In [15]:
arr2 = np.random.randint(50, size=(10,10))
arr2

array([[21, 11,  9, 21, 34, 20,  2, 30,  2, 38],
       [10, 28, 45, 44, 30, 21, 36, 46,  2,  0],
       [18, 15,  6, 14, 32, 47, 34,  4,  0, 46],
       [18, 33,  5, 29, 22, 33, 18, 34, 41, 33],
       [24,  2, 33, 25,  1,  6, 25, 33, 39,  0],
       [ 4, 20,  1, 23,  3,  0, 25,  0, 35, 36],
       [ 1, 37, 35, 21,  6,  9, 49, 36, 30, 35],
       [10, 32, 41, 39,  8, 16, 30, 17, 36, 19],
       [45, 17, 19, 46, 27, 16, 19, 18, 16, 49],
       [43, 23, 20, 13, 28, 47, 29,  4, 38, 15]])

In [16]:
print(np.min(arr2))
print(np.max(arr2))

0
49


## Q.6.Create a random vector of size 30 and find the mean value.

In [28]:
from numpy.random import random
arr3 = random(10)
print(f"list of array: {arr3}")
print(f"Mean of array: {arr3.mean()}")

list of array: [0.16483547 0.43050268 0.71111153 0.3926706  0.75399507 0.20913507
 0.3952105  0.54505673 0.02671303 0.8583197 ]
Mean of array: 0.448755038737543
